"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import {
  Activity, AlertTriangle, Bell, CheckCircle2, ChevronRight, Edit3, Filter, Gauge,
  LayoutDashboard, LogOut, Menu, Plus, Search, Settings, ShieldCheck, TicketCheck,
  Tickets, Users, Wifi, X
} from "lucide-react";

type Priority = "Urgente" | "Haute" | "Moyenne" | "Faible";
type Status = "Nouveau" | "En cours" | "En attente" | "Résolu" | "Fermé";
type View = "dashboard" | "tickets" | "team" | "settings";
type Ticket = { id:string; subject:string; requester:string; department:string; priority:Priority; status:Status; technician:string; description:string; updatedAt:string };

const initialTickets: Ticket[] = [
  { id:"INC-1048", subject:"Accès VPN impossible en télétravail", requester:"Claire Robert", department:"Finance", priority:"Urgente", status:"Nouveau", technician:"Non assigné", description:"Le client VPN affiche une erreur d’authentification depuis ce matin.", updatedAt:"Il y a 8 min" },
  { id:"INC-1047", subject:"Impossible d’imprimer en salle B12", requester:"Marie Dupont", department:"Formation", priority:"Haute", status:"En cours", technician:"Christian Martin", description:"L’imprimante réseau ne répond plus pour les postes de la salle B12.", updatedAt:"Il y a 12 min" },
  { id:"INC-1046", subject:"Compte Microsoft 365 bloqué", requester:"Thomas Bernard", department:"Commerce", priority:"Urgente", status:"Nouveau", technician:"Non assigné", description:"Le compte est verrouillé après plusieurs tentatives de connexion.", updatedAt:"Il y a 25 min" },
  { id:"INC-1045", subject:"Wi-Fi instable au bâtiment C", requester:"Sophie Leroy", department:"Logistique", priority:"Moyenne", status:"En attente", technician:"Emma Petit", description:"Déconnexions fréquentes au deuxième étage du bâtiment C.", updatedAt:"Il y a 1 h" },
  { id:"INC-1044", subject:"Installation du logiciel GLPI", requester:"Hugo Moreau", department:"DSI", priority:"Faible", status:"Résolu", technician:"Christian Martin", description:"Installation du client et vérification de l’inventaire automatique.", updatedAt:"Il y a 2 h" },
  { id:"INC-1043", subject:"Écran externe non détecté", requester:"Nadia Cohen", department:"RH", priority:"Moyenne", status:"En cours", technician:"Emma Petit", description:"L’écran HDMI n’est plus reconnu après une mise à jour Windows.", updatedAt:"Hier, 16:42" },
  { id:"INC-1042", subject:"Droits dossier partagé Projets", requester:"Alexandre Roy", department:"Bureau d’études", priority:"Haute", status:"En attente", technician:"Christian Martin", description:"L’utilisateur doit accéder en lecture au dossier Projets 2026.", updatedAt:"Hier, 15:10" },
  { id:"INC-1041", subject:"Mise à jour antivirus poste COM-07", requester:"Julie Simon", department:"Commerce", priority:"Faible", status:"Fermé", technician:"Emma Petit", description:"Mise à jour des signatures et analyse complète demandées.", updatedAt:"18 juil., 11:35" },
];
const priorities: Priority[] = ["Urgente","Haute","Moyenne","Faible"];
const statuses: Status[] = ["Nouveau","En cours","En attente","Résolu","Fermé"];
const emptyTicket: Omit<Ticket,"id"|"updatedAt"> = { subject:"", requester:"", department:"", priority:"Moyenne", status:"Nouveau", technician:"Non assigné", description:"" };

export default function Home() {
  const [tickets,setTickets] = useState<Ticket[]>(initialTickets);
  const [view,setView] = useState<View>("dashboard");
  const [search,setSearch] = useState("");
  const [priority,setPriority] = useState<Priority|"Toutes">("Toutes");
  const [status,setStatus] = useState<Status|"Tous">("Tous");
  const [modal,setModal] = useState<"create"|"edit"|null>(null);
  const [active,setActive] = useState<Ticket|null>(null);
  const [form,setForm] = useState(emptyTicket);
  const [toast,setToast] = useState("");
  const [mobileNav,setMobileNav] = useState(false);
  const storageReady = useRef(false);

  useEffect(() => { const timer=setTimeout(()=>{const saved=localStorage.getItem("novatech-tickets");if(saved)try{setTickets(JSON.parse(saved))}catch{}storageReady.current=true},0);return()=>clearTimeout(timer) },[]);
  useEffect(() => { if(storageReady.current)localStorage.setItem("novatech-tickets",JSON.stringify(tickets)) },[tickets]);
  useEffect(() => { if(!toast)return; const timer=setTimeout(()=>setToast(""),2800); return()=>clearTimeout(timer) },[toast]);
  const filtered = useMemo(() => { const q=search.trim().toLowerCase(); return tickets.filter(t => (!q||[t.id,t.subject,t.requester,t.technician].some(v=>v.toLowerCase().includes(q)))&&(priority==="Toutes"||t.priority===priority)&&(status==="Tous"||t.status===status)) },[tickets,search,priority,status]);
  const counts={ open:tickets.filter(t=>!["Résolu","Fermé"].includes(t.status)).length, active:tickets.filter(t=>t.status==="En cours").length, urgent:tickets.filter(t=>t.priority==="Urgente"&&!["Résolu","Fermé"].includes(t.status)).length, resolved:tickets.filter(t=>["Résolu","Fermé"].includes(t.status)).length };
  const go=(next:View)=>{setView(next);setMobileNav(false)};
  const openCreate=()=>{setActive(null);setForm(emptyTicket);setModal("create")};
  const openEdit=(t:Ticket)=>{setActive(t);setForm({subject:t.subject,requester:t.requester,department:t.department,priority:t.priority,status:t.status,technician:t.technician,description:t.description});setModal("edit")};
  function submit(e:FormEvent){e.preventDefault();if(modal==="edit"&&active){setTickets(all=>all.map(t=>t.id===active.id?{...t,...form,updatedAt:"À l’instant"}:t));setToast(`${active.id} a été mis à jour.`)}else{const max=Math.max(...tickets.map(t=>Number(t.id.replace("INC-",""))),1040);const created={...form,id:`INC-${max+1}`,updatedAt:"À l’instant"};setTickets(all=>[created,...all]);setToast(`${created.id} a été créé.`)}setModal(null)}
  const closeTicket=(t:Ticket)=>{setTickets(all=>all.map(x=>x.id===t.id?{...x,status:"Fermé",updatedAt:"À l’instant"}:x));setToast(`${t.id} a été fermé.`)};
  const date=new Intl.DateTimeFormat("fr-FR",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date());

  return <div className="app-shell">
    <button className="mobile-menu" aria-label="Ouvrir le menu" onClick={()=>setMobileNav(true)}><Menu/></button>
    <aside className={`sidebar ${mobileNav?"is-open":""}`}><button className="close-mobile" aria-label="Fermer le menu" onClick={()=>setMobileNav(false)}><X/></button>
      <div className="brand"><span className="brand-mark">N</span><div><strong>HelpDesk</strong><span>NovaTech</span></div></div>
      <nav aria-label="Navigation principale"><Nav active={view==="dashboard"} icon={<LayoutDashboard/>} label="Tableau de bord" onClick={()=>go("dashboard")}/><Nav active={view==="tickets"} icon={<Tickets/>} label="Tickets" badge={counts.open} onClick={()=>go("tickets")}/><Nav active={view==="team"} icon={<Users/>} label="Équipe" onClick={()=>go("team")}/><Nav active={view==="settings"} icon={<Settings/>} label="Paramètres" onClick={()=>go("settings")}/></nav>
      <div className="profile-card"><div className="avatar">CM</div><div><strong>Christian Martin</strong><span>Technicien junior</span></div><button><LogOut/><span>Déconnexion</span></button></div>
    </aside>{mobileNav&&<button className="backdrop" aria-label="Fermer le menu" onClick={()=>setMobileNav(false)}/>} 
    <main className="main-content"><header className="topbar"><div><p className="eyebrow">Centre de services IT</p><h1>{view==="dashboard"?"Bonjour Christian":view==="tickets"?"Gestion des tickets":view==="team"?"Équipe support":"Paramètres"}</h1><p className="date">{date[0].toUpperCase()+date.slice(1)}</p></div><div className="top-actions"><button className="icon-button" aria-label="Notifications"><Bell/><span>3</span></button><button className="primary-button" onClick={openCreate}><Plus/>Nouveau ticket</button><div className="top-avatar">CM</div></div></header>
      {view==="dashboard"&&<Dashboard tickets={tickets} counts={counts} showTickets={()=>go("tickets")} onEdit={openEdit}/>} 
      {view==="tickets"&&<TicketsView tickets={filtered} total={tickets.length} search={search} setSearch={setSearch} priority={priority} setPriority={setPriority} status={status} setStatus={setStatus} onEdit={openEdit} onClose={closeTicket} onCreate={openCreate}/>} 
      {view==="team"&&<Team tickets={tickets}/>} {view==="settings"&&<SettingsView onReset={()=>{setTickets(initialTickets);setToast("Les données de démonstration ont été restaurées.")}}/>}
    </main>
    {modal&&<TicketModal mode={modal} form={form} setForm={setForm} onSubmit={submit} onClose={()=>setModal(null)}/>} {toast&&<div className="toast" role="status"><CheckCircle2/>{toast}</div>}
  </div>
}

function Nav({active,icon,label,badge,onClick}:{active:boolean;icon:React.ReactNode;label:string;badge?:number;onClick:()=>void}){return <button className={`nav-item ${active?"active":""}`} onClick={onClick}>{icon}<span>{label}</span>{badge!==undefined&&<em>{badge}</em>}</button>}

function Dashboard({tickets,counts,showTickets,onEdit}:{tickets:Ticket[];counts:{open:number;active:number;urgent:number;resolved:number};showTickets:()=>void;onEdit:(t:Ticket)=>void}){
 const cards=[{label:"Tickets ouverts",value:counts.open,detail:"+2 cette semaine",icon:<Tickets/>,tone:"cyan"},{label:"En cours",value:counts.active,detail:"Traitement actif",icon:<Activity/>,tone:"amber"},{label:"Urgents",value:counts.urgent,detail:"À prendre en charge",icon:<AlertTriangle/>,tone:"red"},{label:"Résolus",value:counts.resolved,detail:"Ce mois-ci",icon:<CheckCircle2/>,tone:"green"}];
 return <><section className="kpi-grid">{cards.map(c=><button key={c.label} className="kpi-card" onClick={showTickets}><span className={`kpi-icon ${c.tone}`}>{c.icon}</span><span><small>{c.label}</small><strong>{c.value}</strong><em>{c.detail}</em></span><ChevronRight className="kpi-arrow"/></button>)}</section><section className="dashboard-grid"><article className="panel ticket-panel"><PanelTitle kicker="File active" title="Tickets récents" action={showTickets}/><TicketTable tickets={tickets.slice(0,5)} onEdit={onEdit} compact/></article><div className="side-stack"><article className="panel priority-panel"><PanelTitle kicker="Vue globale" title="Répartition par priorité"/><div className="priority-content"><div className="donut"><span><strong>{tickets.length}</strong>tickets</span></div><ul>{priorities.map(p=><li key={p}><i className={`dot ${p.toLowerCase()}`}/>{p}<strong>{tickets.filter(t=>t.priority===p).length}</strong></li>)}</ul></div></article><article className="panel"><PanelTitle kicker="Temps réel" title="Activité récente"/><div className="activity-list"><ActivityItem icon={<Plus/>} title="Nouveau ticket créé" text="INC-1048 · Claire Robert" time="8 min"/><ActivityItem icon={<Activity/>} title="Statut mis à jour" text="INC-1047 · En cours" time="12 min"/><ActivityItem icon={<CheckCircle2/>} title="Ticket résolu" text="INC-1044 · Christian Martin" time="2 h"/></div></article></div></section></>
}
function PanelTitle({kicker,title,action}:{kicker:string;title:string;action?:()=>void}){return <div className="panel-heading"><div><p className="section-kicker">{kicker}</p><h2>{title}</h2></div>{action&&<button className="text-button" onClick={action}>Voir tous <ChevronRight/></button>}</div>}

function TicketsView({tickets,total,search,setSearch,priority,setPriority,status,setStatus,onEdit,onClose,onCreate}:{tickets:Ticket[];total:number;search:string;setSearch:(v:string)=>void;priority:Priority|"Toutes";setPriority:(v:Priority|"Toutes")=>void;status:Status|"Tous";setStatus:(v:Status|"Tous")=>void;onEdit:(t:Ticket)=>void;onClose:(t:Ticket)=>void;onCreate:()=>void}){return <section><div className="summary-strip"><div><span>Total</span><strong>{total}</strong></div><div><span>Affichés</span><strong>{tickets.length}</strong></div><div><span>SLA respecté</span><strong>92%</strong></div><div><span>Temps moyen</span><strong>2 h 18</strong></div></div><article className="panel all-tickets"><div className="panel-heading ticket-tools"><div><p className="section-kicker">Centre de support</p><h2>Tous les tickets</h2></div><div className="filters"><label className="search-field"><Search/><span className="sr-only">Rechercher</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ID, sujet, demandeur…"/></label><label><Filter/><span className="sr-only">Priorité</span><select value={priority} onChange={e=>setPriority(e.target.value as Priority|"Toutes")}><option>Toutes</option>{priorities.map(p=><option key={p}>{p}</option>)}</select></label><label><Gauge/><span className="sr-only">Statut</span><select value={status} onChange={e=>setStatus(e.target.value as Status|"Tous")}><option>Tous</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></label></div></div>{tickets.length?<TicketTable tickets={tickets} onEdit={onEdit} onClose={onClose}/>:<div className="empty-state"><Search/><h3>Aucun ticket trouvé</h3><p>Modifiez les filtres ou créez une nouvelle demande.</p><button className="primary-button" onClick={onCreate}><Plus/>Nouveau ticket</button></div>}</article></section>}

function TicketTable({tickets,onEdit,onClose,compact=false}:{tickets:Ticket[];onEdit:(t:Ticket)=>void;onClose?:(t:Ticket)=>void;compact?:boolean}){return <div className="table-wrap"><table><thead><tr><th>Ticket</th><th>Sujet</th><th>Priorité</th><th>Statut</th><th>Technicien</th><th>Mis à jour</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{tickets.map(t=><tr key={t.id}><td><button className="ticket-id" onClick={()=>onEdit(t)}>{t.id}</button></td><td><button className="subject-cell" onClick={()=>onEdit(t)}><strong>{t.subject}</strong><span>{t.requester} · {t.department}</span></button></td><td><Badge type="priority" value={t.priority}/></td><td><Badge type="status" value={t.status}/></td><td>{t.technician}</td><td>{t.updatedAt}</td><td><div className="row-actions"><button onClick={()=>onEdit(t)} aria-label={`Modifier ${t.id}`}><Edit3/></button>{!compact&&onClose&&t.status!=="Fermé"&&<button onClick={()=>onClose(t)} aria-label={`Fermer ${t.id}`}><TicketCheck/></button>}</div></td></tr>)}</tbody></table></div>}
function Badge({type,value}:{type:"priority"|"status";value:string}){return <span className={`badge ${type}-${value.toLowerCase().replace(" ","-").replace("é","e")}`}>{value}</span>}
function ActivityItem({icon,title,text,time}:{icon:React.ReactNode;title:string;text:string;time:string}){return <div className="activity-item"><span>{icon}</span><div><strong>{title}</strong><p>{text}</p></div><time>{time}</time></div>}

function TicketModal({mode,form,setForm,onSubmit,onClose}:{mode:"create"|"edit";form:typeof emptyTicket;setForm:React.Dispatch<React.SetStateAction<typeof emptyTicket>>;onSubmit:(e:FormEvent)=>void;onClose:()=>void}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div className="modal-header"><div><p className="section-kicker">HelpDesk NovaTech</p><h2 id="modal-title">{mode==="create"?"Créer un ticket":"Modifier le ticket"}</h2></div><button onClick={onClose} aria-label="Fermer la fenêtre"><X/></button></div><form onSubmit={onSubmit} className="ticket-form"><label className="span-2">Sujet<input required maxLength={100} value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} placeholder="Ex. Accès VPN impossible"/></label><label>Demandeur<input required value={form.requester} onChange={e=>setForm({...form,requester:e.target.value})} placeholder="Nom et prénom"/></label><label>Service<input value={form.department} onChange={e=>setForm({...form,department:e.target.value})} placeholder="Ex. Finance"/></label><label>Priorité<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as Priority})}>{priorities.map(p=><option key={p}>{p}</option>)}</select></label><label>Statut<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as Status})}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label className="span-2">Technicien<select value={form.technician} onChange={e=>setForm({...form,technician:e.target.value})}><option>Non assigné</option><option>Christian Martin</option><option>Emma Petit</option><option>Mehdi Laurent</option></select></label><label className="span-2">Description<textarea required rows={5} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Décrivez le problème et son impact…"/></label><div className="form-actions span-2"><button type="button" className="secondary-button" onClick={onClose}>Annuler</button><button className="primary-button" type="submit"><CheckCircle2/>{mode==="create"?"Créer le ticket":"Enregistrer"}</button></div></form></section></div>}

function Team({tickets}:{tickets:Ticket[]}){const members=[{initials:"CM",name:"Christian Martin",role:"Technicien junior",color:"cyan"},{initials:"EP",name:"Emma Petit",role:"Administratrice systèmes",color:"blue"},{initials:"ML",name:"Mehdi Laurent",role:"Responsable support",color:"green"}];return <section><div className="team-grid">{members.map(m=><article className="panel team-card" key={m.name}><div className={`avatar large ${m.color}`}>{m.initials}</div><h2>{m.name}</h2><p>{m.role}</p><div><span>Tickets actifs</span><strong>{tickets.filter(t=>t.technician===m.name&&!["Résolu","Fermé"].includes(t.status)).length}</strong></div><span className="availability"><i/>Disponible</span></article>)}</div></section>}
function SettingsView({onReset}:{onReset:()=>void}){return <section className="settings-grid"><article className="panel settings-card"><span className="settings-icon"><ShieldCheck/></span><div><h2>Environnement de démonstration</h2><p>Les tickets sont enregistrés dans le navigateur. Vous pouvez restaurer les données initiales à tout moment.</p><button className="secondary-button" onClick={onReset}>Réinitialiser les données</button></div></article><article className="panel settings-card"><span className="settings-icon"><Wifi/></span><div><h2>État des services</h2><p>API HelpDesk, messagerie et annuaire : tous les services sont opérationnels.</p><span className="service-ok"><i/>Tous les systèmes opérationnels</span></div></article></section>}