create type public.app_role as enum ('requester', 'technician', 'administrator');
create type public.ticket_priority as enum ('low', 'medium', 'high', 'urgent');
create type public.ticket_status as enum ('new', 'in_progress', 'waiting', 'resolved', 'closed');

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
grant usage on schema private to authenticated;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null check (char_length(full_name) between 2 and 100),
  department text,
  role public.app_role not null default 'requester',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.tickets (
  id uuid primary key default gen_random_uuid(),
  ticket_number bigint generated by default as identity (start with 1041),
  subject text not null check (char_length(subject) between 3 and 150),
  description text not null check (char_length(description) between 3 and 5000),
  department text,
  priority public.ticket_priority not null default 'medium',
  status public.ticket_status not null default 'new',
  requester_id uuid not null references public.profiles(id),
  assigned_to uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  closed_at timestamptz,
  unique (ticket_number)
);

create table public.comments (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  author_id uuid not null references public.profiles(id),
  body text not null check (char_length(body) between 1 and 3000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.ticket_history (
  id bigint generated always as identity primary key,
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  changes jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index tickets_requester_idx on public.tickets(requester_id);
create index tickets_assigned_idx on public.tickets(assigned_to);
create index tickets_updated_idx on public.tickets(updated_at desc);
create index comments_ticket_idx on public.comments(ticket_id, created_at);
create index history_ticket_idx on public.ticket_history(ticket_id, created_at desc);

create function private.current_role()
returns public.app_role
language sql
stable
security definer
set search_path = ''
as $$
  select role from public.profiles where id = (select auth.uid())
$$;
revoke all on function private.current_role() from public;
grant execute on function private.current_role() to authenticated;

create function private.can_access_ticket(target_ticket uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.tickets t
    where t.id = target_ticket
      and (
        t.requester_id = (select auth.uid())
        or private.current_role() in ('technician', 'administrator')
      )
  )
$$;
revoke all on function private.can_access_ticket(uuid) from public;
grant execute on function private.can_access_ticket(uuid) to authenticated;

create function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name, department)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''), split_part(new.email, '@', 1)),
    nullif(trim(new.raw_user_meta_data ->> 'department'), '')
  );
  return new;
end;
$$;
revoke all on function private.handle_new_user() from public, anon, authenticated;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_user();

create function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_updated_at before update on public.profiles
for each row execute function private.set_updated_at();
create trigger tickets_updated_at before update on public.tickets
for each row execute function private.set_updated_at();
create trigger comments_updated_at before update on public.comments
for each row execute function private.set_updated_at();

create function private.protect_profile_role()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.role is distinct from old.role
     and coalesce(private.current_role(), 'requester'::public.app_role) <> 'administrator' then
    raise exception 'Seul un administrateur peut modifier un rôle';
  end if;
  return new;
end;
$$;
revoke all on function private.protect_profile_role() from public, anon, authenticated;

create trigger profiles_protect_role before update on public.profiles
for each row execute function private.protect_profile_role();

create function private.log_ticket_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  event_name text;
  payload jsonb;
begin
  if tg_op = 'INSERT' then
    event_name := 'created';
    payload := jsonb_build_object('status', new.status, 'priority', new.priority);
  else
    event_name := 'updated';
    payload := jsonb_strip_nulls(jsonb_build_object(
      'status', case when new.status is distinct from old.status then jsonb_build_object('from', old.status, 'to', new.status) end,
      'priority', case when new.priority is distinct from old.priority then jsonb_build_object('from', old.priority, 'to', new.priority) end,
      'assigned_to', case when new.assigned_to is distinct from old.assigned_to then jsonb_build_object('from', old.assigned_to, 'to', new.assigned_to) end,
      'subject', case when new.subject is distinct from old.subject then jsonb_build_object('from', old.subject, 'to', new.subject) end
    ));
    if payload = '{}'::jsonb then
      event_name := 'content_updated';
    end if;
  end if;

  insert into public.ticket_history (ticket_id, actor_id, action, changes)
  values (new.id, (select auth.uid()), event_name, payload);
  return new;
end;
$$;
revoke all on function private.log_ticket_change() from public, anon, authenticated;

create trigger tickets_audit
after insert or update on public.tickets
for each row execute function private.log_ticket_change();

create function private.log_comment()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.ticket_history (ticket_id, actor_id, action, changes)
  values (new.ticket_id, (select auth.uid()), 'commented', jsonb_build_object('comment_id', new.id));
  return new;
end;
$$;
revoke all on function private.log_comment() from public, anon, authenticated;

create trigger comments_audit after insert on public.comments
for each row execute function private.log_comment();

alter table public.profiles enable row level security;
alter table public.tickets enable row level security;
alter table public.comments enable row level security;
alter table public.ticket_history enable row level security;

create policy profiles_select on public.profiles for select to authenticated
using (id = (select auth.uid()) or private.current_role() in ('technician', 'administrator'));
create policy profiles_update on public.profiles for update to authenticated
using (id = (select auth.uid()) or private.current_role() = 'administrator')
with check (id = (select auth.uid()) or private.current_role() = 'administrator');

create policy tickets_select on public.tickets for select to authenticated
using (requester_id = (select auth.uid()) or private.current_role() in ('technician', 'administrator'));
create policy tickets_insert on public.tickets for insert to authenticated
with check (
  requester_id = (select auth.uid())
  and (assigned_to is null or private.current_role() in ('technician', 'administrator'))
);
create policy tickets_update_staff on public.tickets for update to authenticated
using (private.current_role() in ('technician', 'administrator'))
with check (private.current_role() in ('technician', 'administrator'));
create policy tickets_delete_admin on public.tickets for delete to authenticated
using (private.current_role() = 'administrator');

create policy comments_select on public.comments for select to authenticated
using (private.can_access_ticket(ticket_id));
create policy comments_insert on public.comments for insert to authenticated
with check (author_id = (select auth.uid()) and private.can_access_ticket(ticket_id));
create policy comments_update_own on public.comments for update to authenticated
using (author_id = (select auth.uid()))
with check (author_id = (select auth.uid()));
create policy comments_delete_own_or_admin on public.comments for delete to authenticated
using (author_id = (select auth.uid()) or private.current_role() = 'administrator');

create policy history_select on public.ticket_history for select to authenticated
using (private.can_access_ticket(ticket_id));

grant select, update on public.profiles to authenticated;
grant select, insert, update, delete on public.tickets to authenticated;
grant usage, select on sequence public.tickets_ticket_number_seq to authenticated;
grant select, insert, update, delete on public.comments to authenticated;
grant select on public.ticket_history to authenticated;

comment on table public.ticket_history is 'Journal d audit immuable alimenté par des déclencheurs.';
